release: v0.1.1
linebender/vello_svg pull request #14
Opened 2024-05-25 20:43 UTC by simbleau

Minor patch release to fix view-boxes.

2024-05-25 22:07 UTC, DJMcNab approved these changes
I have not confirmed that the new version number is correct, but it's good to be doing more regular releases.

2024-05-25 22:07 UTC, DJMcNab commented on CHANGELOG.md
> +- Disable `vello`'s default `wgpu` feature, and provide a `wgpu` passthrough feature to turn it back on. [#10](https://github.com/linebender/vello_svg/pull/10)
This is a default feature, right?

2024-05-25 22:10 UTC, simbleau commented
I don't want to do semver with this- I want to keep parity with Vello.

In other words, vello_svg 0.1.X pairs with Vello 0.1

2024-05-25 23:53 UTC, merged

2024-05-26 07:32 UTC, DJMcNab requested changes
> Semver also really only applies after 1.0

Rust (and, except for these cases, Linebender) uses a [modified definition](https://doc.rust-lang.org/cargo/reference/semver.html) of semver which makes semver apply before 1.0. cargo is implemented using this version of semver, and so this change has the possibility of breaking our users e.g. in CI.

In this case the breaking change is minor enough that I'm not immediately yanking 0.1.1. But I also don't want a  repeat of this before we have consensus that this is the direction we want to take.
If we do decide to follow this versioning scheme, we need to document that users SHOULD pin the version of `vello_svg` they depend on.

Rejecting to dismiss my prior approval